stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train.csv
    params:
      - data_preprocessing
    outs:
      - data/processed/train_processed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/train_processed.csv
    params:
      - feature_engineering
    outs:
      - data/features/train_features.csv

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/features/train_features.csv
    params:
      - model_building
    outs:
      - models

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models
      - data/features/train_features.csv
    params:
      - model_evaluation
    outs:
      - reports
