data_ingestion:
  data_url: "https://raw.githubusercontent.com/Narottam-kumar12/Datasets/refs/heads/main/weatherAUS.csv"
  test_size: 0.2
  random_state: 2

data_preprocessing:
  numeric_strategy: median
  categorical_strategy: mode

feature_engineering:
  drop_columns:
    - Rainfall
  create_features:
    temp_range: true
    avg_humidity: true
    pressure_diff: true
    avg_wind_speed: true

model_building:
  target_column: target
  test_size: 0.2
  random_state: 42

  random_forest:
    n_estimators: 200
    max_depth: 10
    class_weight: balanced
    random_state: 42

  xgboost:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: logloss
    random_state: 42

model_evaluation:
  metrics_output_dir: reports
